### ISSUE TITLE
Reporte Practica

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-architect-Band-hi#1]
[Diagrama UML.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Band-hi/files/7152587/Diagrama.UML.pdf)
[Practica Architect.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Band-hi/files/7152588/Practica.Architect.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación 20/20.
Evaluó: Fernando Miguel López.

**Comment by josealfredo79** [comment]
Solo faltaron los parámetros por valor o por referencia.
